ADMIN_PASSKEY = "mip-admin-2026"
ENCRYPTION_KEY = "gvWFe9sgmVtnha4RgjcQcbpit3ekT39iLPMtCtG1TV8="
DATABASE_URL = "sqlite:///./data/leads.db"
SMTP_ENABLED = true
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "jacobcornell88@gmail.com"
SMTP_PASSWORD = "yspzydzbbutgtxze"
SMTP_FROM_EMAIL = "jacobcornell88@gmail.com"
ALERT_EMAIL_TO = "jacobcornell88@gmail.com"
ORGANIZATION_NAME = "Mutual Income Protection"
